src/main/forms.py
import json
from flask_wtf import FlaskForm
from wtforms import (
    DecimalField,
    EmailField,
    StringField,
    SelectField,
    TextAreaField,
    SubmitField,
    BooleanField,
    HiddenField,
    RadioField,
    IntegerField,
    FieldList,
    FormField,
    DateField,
)
from wtforms.form import BaseForm
from wtforms.validators import DataRequired, Length, NumberRange, Email


class UserProfileForm(FlaskForm):
    given_name = StringField("Given Name", validators=[Length(min=0, max=80)])
    family_name = StringField("Family Name", validators=[Length(min=0, max=80)])
    middle_name = StringField("Middle Name", validators=[Length(min=0, max=80)])
    nickname = StringField("Nickname", validators=[Length(min=0, max=80)])
    birthdate = DateField("Birthdate")
    pronouns = StringField("Pronouns", validators=[Length(min=0, max=80)])


class ProfileSocialMediaForm(FlaskForm):
    handle = StringField("Handle", validators=[Length(min=0, max=80)])
    platform_id = SelectField("Platform", coerce=str)


class ProfileTelephoneNumbersForm(FlaskForm):
    phone = StringField("Phone", validators=[Length(min=0, max=80)])
    is_default = BooleanField("Default")


class UserProfileEmailsForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Length(min=1, max=80)])
    is_default = BooleanField("Default")


class ProfileLocationsForm(FlaskForm):
    street1 = StringField("Street 1", validators=[Length(min=0, max=80)])
    street2 = StringField("Street 2", validators=[Length(min=0, max=80)])
    city = StringField("City", validators=[Length(min=0, max=80)])
    state = StringField("State", validators=[Length(min=0, max=80)])
    postal_code = StringField("Postal Code", validators=[Length(min=0, max=80)])
    country = StringField("Country", validators=[Length(min=0, max=80)])
    is_default = BooleanField("Default")


class ProfileRatingChangeForm(FlaskForm):
    change = StringField("Change", validators=[Length(min=0, max=10240)])
    social_rating_change = IntegerField("Social Credit Score Change", validators=[NumberRange(min=0)], default=0)
    antisocial_rating_change = IntegerField("Anti-social credit Score Change", validators=[NumberRange(min=0)], default=0)


class UserProfileAdminForm(UserProfileForm):
    is_active = BooleanField("Active")
    user_since = DateField("User Since")
    is_admin = BooleanField("Admin")


class OrganizationProfileForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=1, max=80)])
    dba = StringField("DBA", validators=[Length(min=0, max=2048)])
    is_active = BooleanField("Active")


class OrganizationContactUserForm(FlaskForm):
    given_name = StringField("Given Name", validators=[Length(min=0, max=80)])
    family_name = StringField("Family Name", validators=[Length(min=0, max=80)])
    middle_name = StringField("Middle Name", validators=[Length(min=0, max=80)])
    nickname = StringField("Nickname", validators=[Length(min=0, max=80)])


class DeleteConfirmForm(FlaskForm):
    confirm = SubmitField("Confirm Delete")


class ProfileTagsForm(FlaskForm):
    tag = SelectField("Tag", coerce=str, validators=[DataRequired()])

src/main/routes.py
from csv import DictWriter
from datetime import date
from time import time
from urllib.parse import quote, unquote

import arrow
import boto3
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
)

from app import app, config
from main.forms import (
    UserProfileForm,
    ProfileSocialMediaForm,
    UserProfileEmailsForm,
    ProfileLocationsForm,
    ProfileRatingChangeForm,
    UserProfileAdminForm,
    OrganizationProfileForm,
    ProfileTelephoneNumbersForm,
    OrganizationContactUserForm,
    DeleteConfirmForm,
    ProfileTagsForm,
)
from models import (
    Users,
    Organizations,
    UserProfile,
    OrganizationProfile,
    SocialMediaAccountProfile,
    SocialMediaPlatforms,
    SocialMediaAccounts,
    EmailAddressProfile,
    PhysicalAddressProfile,
    TelephoneNumberProfile,
    ChangeEventProfile,
    Words,
    Tags,
)
from auth.utils import requires_login_and_group

mod = Blueprint("main", __name__, url_prefix="/")

s3 = boto3.client(
    "s3",
    aws_access_key_id=config.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=config.AWS_SECRET_ACCESS_KEY,
    region_name=config.AWS_DEFAULT_REGION,
)


@mod.route("/")
@requires_login_and_group("Users")
def index():
    return redirect(url_for("main.profile"))


@mod.route("/search/<string:entity_type>")
@requires_login_and_group("Users")
def search_entity(entity_type: str):
    q = request.args.get("q", "")
    terms = [quote(x) for x in q.strip().split(" ")]
    # pagination
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", config.DEFAULT_PER_PAGE, type=int)
    start = time()
    pagination = None
    if entity_type == "user":
        pagination = search_users(terms=terms, page=page, per_page=per_page)
    elif entity_type == "organization":
        pagination = search_organizations(terms=terms, page=page, per_page=per_page)
    else:
        return render_template("error.html", message="Invalid entity type.")

    return render_template(
        "main/search_entities.html",
        pagination=pagination,
        q=q,
        entity_type=entity_type,
        page=page,
        per_page=per_page,
        duration=round(time() - start, 2),
    )


@mod.route("/search")
@requires_login_and_group("Users")
def search():
    q = request.args.get("q", "").replace("'", "").replace('"', "")
    terms = [quote(x) for x in q.strip().split(" ") if x]

    users = []
    organizations = []
    org_count = 0
    user_count = 0
    print("terms", terms)
    if terms:
        organizations = search_organizations(terms=terms)
        users = search_users(terms)
        org_count = organizations.total
        users = search_users(terms=terms)
        user_count = users.total
    else:
        org_count = Organizations().count()
        user_count = Users().count()
    return render_template(
        "main/search.html", users=users, organizations=organizations, q=q, org_count=org_count, user_count=user_count
    )


def search_users(terms: list[str], page: int = 1, per_page: int = config.DEFAULT_PER_PAGE):
    users = Users().ls()
    social_media_accounts = SocialMediaAccounts().ls()
    matches = {}
    for term in terms:
        if term not in matches:
            matches[term] = []
        for user in users:
            if term.lower() in user.lower():
                matches[term].append(user)
        for sma in social_media_accounts:
            if term.lower() in sma.lower():
                platform, handle = sma.split(":")
                profile = SocialMediaAccounts().get_profile(platform=platform, handle=handle, profile_type="user")
                matches[term].append(profile.name)

    # reduce the users by intersecting the sets of users for each term
    users = set()
    for _, usrs in matches.items():
        if not users:
            users = set(usrs)
        else:
            users = users.intersection(set(usrs))

    users = [UserProfile(name=x, uid="placeholder") for x in sorted(users, key=lambda x: x.lower())]
    return ListPagination(users, page, per_page, len(users))


class StubProfile:
    def __init__(self, name: str):
        self.name = name
        self.id = name


class ListPagination:
    def __init__(self, items: list, page: int, per_page: int, total: int):
        self.items = items[(page - 1) * per_page : page * per_page]
        self.page = page
        self.per_page = per_page
        self.total = total
        self.pages = int(total / per_page) + (1 if total % per_page > 0 else 0)
        self.has_prev = page > 1
        self.has_next = page < self.pages
        self.prev_num = max(1, page - 1)
        self.next_num = min(page + 1, self.pages)


def search_organizations(terms: list[str], page: int = 1, per_page: int = config.DEFAULT_PER_PAGE):
    concat_terms = "".join([x.lower() for x in sorted(terms)])
    organizations = []

    exclude_terms = ["llc", "inc"]
    words_group = Words()
    words = dict()
    for term in [x.lower() for x in terms if x and x not in exclude_terms]:
        word = words_group.get(term)
        if word and "organizations" in word:
            words[term] = word.get("organizations", [])

    # reduce the orgs by intersecting the sets of orgs for each word
    organizations = set()
    for _, orgs in words.items():
        if not organizations:
            organizations = set(orgs)
        else:
            organizations = organizations.intersection(set(orgs))
    organizations = list(organizations)
    organizations = [OrganizationProfile(name=x) for x in sorted(organizations, key=lambda x: x.lower())]
    pagination = ListPagination(organizations, page, per_page, len(organizations))
    return pagination


@mod.route("/profile")
@mod.route("/profile/username/<string:username>")
@requires_login_and_group("Users")
def profile(username=None):
    user = None
    _username = username if username else session["username"]
    if _username is None:
        return redirect(url_for("auth.login"))

    user = Users().get(name=_username)
    if not user:
        return render_template("error.html", message="User not found.")

    return render_template("main/profile.html", profile=user, system_tags=Tags().ls())


@mod.route("/profile/orgname/<string:name>", methods=["GET"])
@requires_login_and_group("Users")
def profile_organization(name: str):
    organization = Organizations().get(name)
    if name is None:
        return render_template("error.html", message="Organization not found.")
    print("organization", organization, type(organization))
    return render_template("main/profile.html", profile=organization)


@mod.route("/profile/personal/", methods=["GET", "POST"])
@mod.route("/profile/personal/<string:username>", methods=["GET", "POST"])
@requires_login_and_group("Users")
def profile_personal(username=None):
    user = None
    _username = username if username else session["username"]
    if not _username:
        return redirect(url_for("auth.login"))
    if "Admins" not in session.get("groups", []) and _username != session.get("username", None):
        # cannot edit if not an admin or the current logged in user
        return redirect(url_for("main.profile"))
    _username = quote(_username)

    user = Users().get(name=_username)
    if not user:
        return render_template("error.html", message="User not found.")

    form_class = UserProfileForm

    if "Admins" in session.get("groups", []) and username != session.get("username", None):
        # use admin form if admin and not editing own profile
        form_class = UserProfileAdminForm

    form = form_class()
    user.birthdate = arrow.get(user.birthdate or "1900-01-01").date()
    user.user_since = arrow.get(user.user_since or "1900-01-01").date()
    if request.method == "GET":
        form = form_class(obj=user)

    if form_class == UserProfileAdminForm:
        if user.name == session.get("username", None):
            # if current user is admin and editing own profile, do not allow editing of is_admin
            form.is_admin.render_kw = {"disabled": True}
        form.is_admin.data = "Admins" in user.groups

    if form.validate_on_submit():
        for k in [x for x in form.data.keys() if x not in ["user_since", "birthdate", "csrf_token", "is_admin"]]:
            v = form.data.get(k, None)
            if v is not None:
                setattr(user, k, v)

        birthdate = str(form.birthdate.data)
        if birthdate > "1900-01-01":
            user.birthdate = birthdate

        if form_class == UserProfileAdminForm:
            if user.name != session.get("username", None):
                # if current user is admin and not editing own profile, allow editing of is_admin
                if request.form.get("is_admin", None) == "y":
                    if "Admins" not in user.groups:
                        user.groups.append("Admins")
                else:
                    if "Admins" in user.groups:
                        user.groups = [x for x in user.groups if x != "Admins"]
            if form.user_since.data and str(form.user_since.data) > "1900-01-01":
                user.user_since = str(form.user_since.data)
            user.is_active = request.form.get("is_active", None) == "y"
            form.is_active.data = user.is_active
            form.is_admin.data = "Admins" in user.groups
        Users().update(user_profile=user)
        return redirect(url_for("main.profile", username=user.name))
    print("user", user)
    return render_template(
        "main/profile-update.html", profile=user, form=form, update_type="personal", update_verb="Update"
    )


def can_access(username: str = None):
    is_admin = "Admins" in session.get("groups", [])
    if is_admin:
        return True
    if username is None:
        return False
    return username == session.get("username", None)


# create route for profile_social_media

src/templates/main/profile-update.html
{% extends "base.html" %}

{% block content %}
{% set return_url=url_for('main.profile', username=profile.name|url_quote) if profile|is_user else url_for('main.profile_organization', name=profile.name|url_quote) %}
<div class="profile">
    <div class="profile-header">
        {% if is_admin and profile.name and profile.name!=session['username'] %}
        <div class="warning">Editing {{profile_type}} {{profile_name}} - <a href="{{return_url}}">see changes</a></div>
        {% endif %}
        <button class="small-button back-button" onclick="window.location.href='{{return_url}}'">Back</button>
        <h2>{{update_verb}} {{update_type|title}} information for {{profile.name}}</h2>
    </div>

    <div class="form-update">
        <form class="form" action="" method="POST">
            {{form.csrf_token}}
            <div class="form-fields">
                <table class="form-details">
                {% for field in form %}
                    <tr>
                        {% if field.type!='CSRFTokenField' %}
                        <td class="field-name">{{field.label}}</td>
                        <td class="field-value">{{field(class="error" if field.errors else "")}}</td>
                        {%if field.errors%}<span class="error-detail">{{field.errors|join(',')}}{%endif%}</span></td>
                        {%endif%}
                    </tr>
                {% endfor %}
                </table>
            </div>
            <br/>
            <p><input type="submit" value="{{update_verb}}"></p>
        </form>
    </div>
</div>

{% endblock %}

src/templates/main/profile.html
{% extends "base.html" %}

{% block content %}

{% set is_admin = "Admins" in session['groups'] %}
{% set can_edit = (profile.name and profile.name==session['username']) or is_admin %}
{% set return_url=url_for('main.profile', username=profile.username|url_quote) if profile|is_user else url_for('main.profile_organization', name=profile.name|url_quote) %}
{% set pii_note="This information cannot be viewed by other users."%}
<div class="profile">
    {% if is_admin and profile.name and profile.name!=session['username'] %}
    <div class="warning">Admin view of {{profile|profile_type}} {{profile.name}}</div>
    {% endif %}
    <div class="profile-header">
        <p class="profile-name">{%if profile.is_blocked%}🚫{%endif%}{% if profile|is_user%}{%if profile.is_premium_user%}⭐{%else%}⚠️👤{%endif%}{%else%}🏢{%endif%} {{profile.name}}</p>
        {% if profile.social_rating %}
        <p class="profile-description">
            Social Credit score: {{profile.social_rating}}
        </p>
        {% endif %}
        {% if profile.antisocial_rating %}
        <p class="profile-description">
            Anti-social credit score: {{profile.antisocial_rating}}
        </p>
        {% endif %}    
        {% if profile.tags %}
        <div>
            Tags: 
            {% for tag in profile.tags %}
            <span class="tag">{{tag}}</span>
            {% endfor %}
        </div>
        {% endif %}            
        <p class="profile-description">
            {% if is_admin and profile.name!=session['username'] %}
            <div>
                <a 
                    class="dark-link small-link" 
                    style="margin-left:1em;" 
                    href="{{url_for('main.profile_rating_change', profile_name=profile.name|url_quote, profile_type=profile|profile_type)}}">
                        Change score
                </a>
            </div>
            {% endif %}


        </p>
    </div>
    <div class="tabs">
        {% if profile|is_org %}
        <button class="tab active" onclick="openTab(event, 'Organization')">Organization</button>
        {% endif %}
        <button class="tab {% if profile|is_user%}active{%endif%}" onclick="openTab(event, 'Social Media')">Social Media</button>
        {% if can_edit and profile|is_user %}
        <button class="tab" onclick="openTab(event, 'Personal')">Personal</button>
        {%endif%}
        {% if can_edit or not profile|is_user %}
        <button class="tab" onclick="openTab(event, 'Location')">Location</button>
        <button class="tab" onclick="openTab(event, 'Email')">Email</button>
        <button class="tab" onclick="openTab(event, 'Phone')">Phone</button>
        <button class="tab" onclick="openTab(event, 'Score History')">Score History</button>
        {% endif %}
        
    </div>


    {% if can_edit and profile|is_user %}
    <div id="Personal" class="tab-content" style="display:none">
        <h2>Personal</h2>
        {% if not is_contact %}<div class="note">{{pii_note}}</div>{% endif %}
        <button class="small-button with-bottom-margin" onclick="window.location.href='{{url_for('main.profile_personal', username=profile_name|url_quote)}}'">Update</button>

        <table class="details">
            <tr>
                <td class="field-name">name</td>
                <td class="field-value">{{profile.name}}</td>
            </tr>
            {% for k,v in profile.__dict__.items() if k not in ['name', 'uid', 'groups', 'tags', 'raw_data', 'social_media_accounts', 'physical_addresses', 'email_addresses', 'telephone_numbers', 'change_events', 'tags', 'social_rating', 'antisocial_rating'] %}
            {% if v %}
            <tr>
                <td class="field-name">{{k}}</td>
                <td class="field-value">{{v}}</td>
            </tr>
            {% endif %}
            {% endfor %}
            {% if profile.groups %}
            <tr>
                <td class="field-name">groups</td>
                <td class="field-value">
                    {% for group in profile.groups %}
                    <span>{{group}}</span>
                    {% endfor %}
                </td>
            </tr>
            {% endif %}
            {% if system_tags %}
            <tr>
                <td class="field-name">
                    tags
                    {% if is_admin %}<button class="small-button with-bottom-margin" onclick="window.location.href='{{url_for('main.profile_tags', profile_type=profile|profile_type, profile_name=profile.name|url_quote)}}'">Add tag</button>{%endif%}
                </td>
                <td>
                    {% for tag in profile.tags %}
                    <span class="tag">
                        {{tag}}
                        {% if is_admin%}
                        <span class="divider"></span>
                        <a class="remove-button" href="{{url_for('main.profile_tags_delete', profile_name=profile.name|url_quote, profile_type=profile|profile_type, tag=tag)}}">X</a>
                        {%endif%}
                    </span>
                    {% endfor %}
                </td>
            </tr>
            {% endif %}
        </table>
    </div>
    {%endif%}
    {% if profile|is_org %}
    <div id="Organization" class="tab-content" style="display:none">
        <h2>Organization</h2>
        
        <table class="details">
            <tr>
                <td class="field-name">name</td>
                <td class="field-value">{{profile.name}}</td>
            </tr>
            <tr>
                <td class="field-name">profile type</td>
                <td class="field-value">{{profile.profile_type}}</td>
            </tr>
            {% if profile.raw_data %}
            <tr>
                <td class="field-name">details</td>
                <td class="field-value">{{profile.raw_data|pretty_json}}</td>
            </tr>           
            {% endif %}
        </table>
    </div>
    {%endif%}


    <div id="Social Media" class="tab-content">
        <h2>Social Media</h2>
        {% if can_edit %}
        <button
            class="small-button with-bottom-margin" 
            onclick="window.location.href='{{url_for('main.profile_social_media', profile_type=profile|profile_type, profile_name=profile.name|url_quote)}}'"
            >Add</button>
        {% endif %}
        {% if profile.social_media_accounts %}
        <table class="details">
            <thead>
                <th>Platform</th>
                <th>Handle</th>
                {% if can_edit %}<th>Action</th>{%endif%}
            </thead>
            {% for sma in profile.social_media_accounts|sort(attribute="handle") %}
            <tr>
                <td class="field-name centered">{{sma.platform}}</td>
                <td class="field-value centered">{{sma.handle}}</td>
                {% if can_edit %}
                <td class="field-value">
                    <a class="dark-link small-link" href="{{url_for('main.profile_social_media', profile_type=profile|profile_type, profile_name=profile.name|url_quote, platform=sma.platform, handle=sma.handle)}}">Edit</a>
                    <a class="dark-link small-link" href="{{url_for('main.profile_social_media_delete', profile_type=profile|profile_type, profile_name=profile.name|url_quote, platform=sma.platform, handle=sma.handle)}}">Delete</a>
                </td>
                {%endif%}
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>

    {% if can_edit or not profile|is_user %}
    <div id="Location" class="tab-content" style="display:none">
        <h2>Location</h2>
        {% if profile|is_user %}
        <div class="note">{{pii_note}}</div>
        {% endif %}
        {% if is_admin or can_edit %}
        <button class="small-button with-bottom-margin" onclick="window.location.href='{{url_for('main.profile_locations', profile_type=profile|profile_type, profile_name=profile.name|url_quote)}}'">Add</button>
        {%endif%}

        {% for entry in profile.physical_addresses|sort(attribute=("street1")) %}
        <div class="entry-title-container">
            <span class="entry-title">{{entry.street1}}</span>
            {% if can_edit %}
            <a class="small-link" href="{{url_for('main.profile_locations', profile_type=profile|profile_type, profile_name=profile.name|url_quote, hash=entry.signature)}}">Edit</a>
            <a class="small-link" href="{{url_for('main.profile_locations_delete', profile_type=profile|profile_type, profile_name=profile.name|url_quote, hash=entry.signature)}}">Delete</a>
            {% endif %}
        </div>  

        <table class="details">
            {{entry.__dict__|pretty_json}}

        </table>        
        {% endfor %}
    </div>

    <div id="Email" class="tab-content" style="display:none">
        <h2>Email</h2>
        {% if profile|is_user %}
        <div class="note">{{pii_note}}</div>
        {% endif %}
        {% if is_admin or can_edit %}
        <button class="small-button with-bottom-margin"
            onclick="window.location.href='{{url_for('main.profile_emails', profile_type=profile|profile_type, profile_name=profile.name|url_quote)}}'">Add</button>
        {%endif%}
        {% if profile.email_addresses%}
        <table class="details">
            <thead>
                <th>Email</th>
                <th>Default</th>
                {% if can_edit %}
                <th>Action</th>
                {% endif %}
            </thead>
            {% for entry in profile.email_addresses|sort(attribute=("email")) %}
            <tr>
                <td class="field-name">{{entry.email}}</td>
                <td class="field-value centered">{% if entry.is_default%}✅{%endif%}</td>
                {% if can_edit %}
                <td class="field-value">
                    <a class="dark-link small-link" href="{{url_for('main.profile_emails', profile_type=profile|profile_type, profile_name=profile.name|url_quote, email=entry.email|url_quote)}}">Edit</a>
                    <a class="dark-link small-link" href="{{url_for('main.profile_emails_delete', profile_type=profile|profile_type, profile_name=profile.name|url_quote, email=entry.email|url_quote)}}">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>        
        {% endif %}

    </div>

    <div id="Phone" class="tab-content" style="display:none">
        <h2>Phone</h2>
        {% if profile|is_user %}
        <div class="note">{{pii_note}}</div>
        {% endif %}
        {% if is_admin or can_edit %}
        <button class="small-button with-bottom-margin" onclick="window.location.href='{{url_for('main.profile_telephone_numbers', profile_type=profile|profile_type, profile_name=profile.name|url_quote)}}'">Add</button>
        {%endif%}

        {% if profile.telephone_numbers %}
        <table class="details">
            <thead>
                <th>Telephone</th>
                <th>Default</th>
                {% if can_edit %}
                <th>Action</th>
                {% endif %}
            </thead>
            {% for entry in profile.telephone_numbers|sort(attribute=("phone")) %}
            <tr>
                <td class="field-name">{{entry.phone}}</td>
                <td class="field-value centered">{% if entry.is_default%}✅{%endif%}</td>
                {% if can_edit %}
                <td class="field-value">
                    <a class="dark-link small-link" href="{{url_for('main.profile_telephone_numbers', profile_type=profile|profile_type, profile_name=profile.name|url_quote, hash=entry.signature)}}">Edit</a>
                    <a class="dark-link small-link" href="{{url_for('main.profile_telephone_numbers_delete', profile_type=profile|profile_type, profile_name=profile.name|url_quote, hash=entry.signature)}}">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>        
        {% endif %}

    </div>

    <div id="Score History" class="tab-content" style="display:none">
        <h2>Score History</h2>
        {% if profile|is_user %}
        <div class="note">{{pii_note}}</div>
        {%endif%}

        {% if is_admin and session['username']!=profile.name%}
        <button class="small-button with-bottom-margin" onclick="window.location.href='{{url_for('main.profile_rating_change', profile_type=profile|profile_type, profile_name=profile.name|url_quote )}}'">Update</button>
        {% endif %}
        {% if profile.change_events %}
        <table class="details">
            <thead>
                <th>Date</th>
                <th>Score change</th>
                <th>Change type</th>
                <th>Changed by</th>
                <th>Comment</th>
            </thead>
            {% for change in profile.change_events|sort(attribute='change_date', reverse=True) %}
            <tr>
                <td class="field-value">{{change.change_date|just_date}}</td>
                <td class="field-value">{{change.social_rating_change+change.antisocial_rating_change}}</td>
                <td class="field-value">{% if change.social_rating_change>0%}Social Credit{%else%}Anti-social credit{%endif%}</td>
                <td class="field-value">{{change.changed_by_user}}</td>
                <td class="field-value">{{change.change}}</td>
            </tr>
            {% endfor %}
        </table>
        {%endif%}

    </div>
    {% endif %}

</div>

{% include 'common/tabmenu.html'%}


{% endblock %}

src/templates/main/search_entities.html
{% extends "base.html" %}

{% block content %}
<div class="profile">
    <div class="profile-header">
        <h2>Search for {{entity_type}}</h2>
        <!-- search form -->
        <form action="" method="GET">
                <div class="search">
                    <input type="text" name="q" placeholder="Search for {{entity_type}}" value="{{request.args.get('q')}}">
                    <button id="search" type="submit">Search</button>
                    <img src="{{url_for('static', filename='img/spinning-hourglass-small.gif')}}" alt="search icon" class="search-icon" style="display:none;width:15px;">
                    <span class="smaller" id="search-results">({{pagination.total}} records in {{duration}} seconds)</span>
                </div>
        </form>
    </div>
    <div classs="search-results">
        {% if pagination %}
        <div id="Results" class="tab-content">
            <h2>{{entity_type|title}}s</h2>
            <h3>Total results: {{pagination.total}}</h3>
            <table class="search-results-table">
                <thead>
                    <th style="width:{%if entity_type=='user'%}15{%else%}70{%endif%}%;text-align: left;">Name</th>
                    <th style="text-align: left;">Profiles</th>
                </thead>
                {% for profile in pagination.items %}
                <tr class="search-row-{% if loop.index0 % 2%}light{%else%}dark{%endif%}">
                    {% if profile|is_user %}
                    <td class="field-name">
                        <a class="dark-link" href="{{url_for('main.profile', username=profile.name|url_quote)}}">
                            {{profile.name}}
                        </a>
                    </td>
                    {%else%}
                    <td class="field-name">
                        <a class="dark-link" href="{{url_for('main.profile_organization', name=profile.name)}}">
                            {{profile.name}}
                        </a>
                    </td>
                    {% endif %}
                    <td class="field-value social-media-account">
                        {% if profile.social_media_accounts %}
                        {% for sma in profile.social_media_accounts[0:3]%}
                        {{sma.platform.name}}:{{sma.handle}}{% if not loop.last %}, {% endif %}
                        {% endfor %}
                        {% if profile.social_media_accounts|length > 3 %} and {{profile.social_media_accounts|length - 3 }} more {% endif %}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
            <!--pagination controls-->
            <div class="pagination">
                {% if pagination.has_prev %}
                    <a class="dark-link" href="{{ url_for('main.search_entity', entity_type=entity_type, page=pagination.prev_num, q=q, per_page=per_page) }}">Previous</a>
                {% endif %}
                {% if pagination.has_next %}
                    <a class="dark-link" href="{{ url_for('main.search_entity', entity_type=entity_type, page=pagination.next_num, q=q, per_page=per_page) }}">Next</a>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
<script>
    document.getElementsByClassName("search-icon")[0].style.display = "none";
    document.getElementById("search").addEventListener("click", function(){
        document.getElementsByClassName("search-icon")[0].style.display = "inline";
        document.getElementById("search-results").innerHTML = "";
    });
</script>
{% endblock %}